import koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * FrameMasuk class represents the login frame.
 */
public class FrameMasuk extends javax.swing.JFrame {

    /**
     * Creates new form FrameMasuk
     */
    public FrameMasuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        input_nik = new javax.swing.JTextField();
        btn_masuk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_nik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_nik.setBorder(null);
        getContentPane().add(input_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 560, 50));

        btn_masuk.setBackground(new java.awt.Color(73, 167, 217));
        btn_masuk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_masuk.setForeground(new java.awt.Color(255, 255, 255));
        btn_masuk.setText("MASUK");
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 573, 360, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_klinik/Masuk.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {
        String nik = input_nik.getText();

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            conn = koneksi.getConnection(); // Pastikan koneksi database sudah ada di package koneksi
            String sql = "SELECT * FROM data_diri WHERE NIK = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, nik);
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login berhasil!");
                keluhan_diri keluhan = new keluhan_diri();
                this.setVisible(false);
                keluhan.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "NIK tidak ditemukan. Silakan daftar terlebih dahulu.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error saat menutup koneksi: " + ex.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_masuk;
    private javax.swing.JTextField input_nik;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
