/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yudas
 */
public class identitas_diri extends javax.swing.JFrame {

    /**
     * Creates new form identitas_diri
     */
    public identitas_diri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_email = new javax.swing.JTextField();
        input_noTelepon = new javax.swing.JTextField();
        input_nama = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        input_nik = new javax.swing.JTextField();
        tombol = new javax.swing.JButton();
        input_ttl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_email.setBorder(null);
        getContentPane().add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 420, -1));

        input_noTelepon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_noTelepon.setBorder(null);
        getContentPane().add(input_noTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 420, -1));

        input_nama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_nama.setBorder(null);
        getContentPane().add(input_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 420, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 420, -1));

        input_nik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_nik.setBorder(null);
        getContentPane().add(input_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 420, -1));

        tombol.setBackground(new java.awt.Color(73, 191, 217));
        tombol.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tombol.setForeground(new java.awt.Color(255, 255, 255));
        tombol.setText("DAFTAR");
        tombol.setAutoscrolls(true);
        tombol.setBorder(null);
        tombol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolActionPerformed(evt);
            }
        });
        getContentPane().add(tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 280, 60));

        input_ttl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_klinik/identitas diri.png"))); // NOI18N
        getContentPane().add(input_ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(identitas_diri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(identitas_diri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(identitas_diri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(identitas_diri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new identitas_diri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_nama;
    private javax.swing.JTextField input_nik;
    private javax.swing.JTextField input_noTelepon;
    private javax.swing.JLabel input_ttl;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tombol;
    // End of variables declaration//GEN-END:variables
}
